# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  server:
    container_name: server
    build:
      context: '.'
      target: base
    ports:
      - '4001:4001'
    depends_on:
      - db
    networks:
      - test_vm
  db:
    image: postgres:13
    restart: always
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: emanuele
      POSTGRES_PASSWORD: 12docker_pwd21!
      POSTGRES_DB: federationdb_test
    networks:
      - test_vm
networks:
  test_vm:
    name: test_vm
    driver: bridge
