version: "3.9"

services:
  server:
    container_name: federation-gateway
    build:
      context: "."
      target: base
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - db
    networks:
      - test_vm
  db:
    container_name: db
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    # expose:
    #   - "5434"
    volumes:
      - ./bin/create-multiple-postgresql-databases:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: federationdb_auth_test,federationdb_common_test
      POSTGRES_USER: emanuele
      POSTGRES_PASSWORD: 12docker_pwd21!
    networks:
      - test_vm
networks:
  test_vm:
    name: test_vm
    driver: bridge
